TCN Train with inception embeddings
OrielBanne/PNN-AI pull request #1
Opened 2020-09-14 19:04 UTC by OrielBanne

enjoy

2020-09-14 19:05 UTC, Snover98 commented on datasets/inception_subset.py
> +    # TODO: this one did not work because getitem gets only one parameter (plant)
commented code?

2020-09-14 19:05 UTC, Snover98 commented on datasets/inception_subset.py
> +    #     return plant_inception
commented code?

2020-09-14 19:40 UTC, Snover98 requested changes

2020-09-14 19:40 UTC, Snover98 commented on model/PlantFeatExtNew.py
> +        return torch.stack([m.t() for m in out])
shouldn't you just use the original one?
I see no difference in this class

2020-09-14 19:40 UTC, Snover98 commented on model/PlantFeatExtNew.py
> +            # print('x[mod].shape after torch.squeeze(x[mod]) ', x[mod].shape)  #torch.Size([4, 57, 2048])
remove commented code

2020-09-19 07:42 UTC, Snover98 requested changes

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +class Modalities(Dataset):
- [ ] rename to something like `ModalitiesInceptionFeaturesDataset`

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +                 **plant_files_dict):
- [ ] add type hints for the start & end dates
- [ ] add type hint to `plant_files_dict`, also consider renaming to `plant_files`

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +        self.experiment = exp_name
- [ ] rename to `self.experiment_name`
```suggestion
        self.experiment_name: str = exp_name
```

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +        self.end_date = end_date.date()
- [ ] add type hints to the fields, so stuff like `self.num_plants: int = len(labels[exp_name])`

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +        self.used_plants = [plant for plant in range(self.num_plants)]
- [ ] use the `list` operator
```suggestion
        self.used_plants: List[int] = list(range(self.num_plants))
```

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +        if data_list is not None:
you can also do
```suggestion
        if data_list:
```
(you can keep it the same if it looks more readable to you right now)

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +                    tensors.append(inception_embedding)
- [ ] use list comprehension
```suggestion
            tensors = [torch.load(file) for file in data_list
            if self.start_date <= self.__get_file_date(file, f'plant_{plant}_', mod) <= self.end_date]
```

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +            print('at least one of the mods is empty, check experiment mods!!!')
why is there a print and not an Exception?

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +        return plant_inception_all_mods
- [ ] use dict comprehension
```suggestion
        return {mod: self.__plant_inception_one_mod(plant, mod) for mod in parameters.used_modalities}
```

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +    def __plant_inception_one_mod(self, plant, mod):
- [ ] type hints for inputs and output
```suggestion
    def __plant_inception_one_mod(self, plant: int, mod: str) -> Optional[torch.tensor]:
```
(add in all places where applicable)

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +            inception=self.__plant_inception_all_mods(plant),
I think that 'inception' is a bit too specific.
maybe change to something like 'features'?

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +        plant = idx % self.num_plants
- [ ] rename to something a bit more specific
```suggestion
        plant_number: int = idx % self.num_plants
```

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +        print('self.plants  = ', self.plants)
- [ ] remove print
```suggestion
```

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +        plant = self.plants[idx % self.num_plants]
- [ ] rename to something a bit more specific
```suggestion
        plant_num = self.plants[idx % self.num_plants]
```

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +        cycle = idx // self.num_plants
what does `cycle` represent?
The name does not really convey that

- [ ] rename to something more meaningful

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +        X = tuple(i for i in range(n_plants))  # Plants by order
- [ ] no need for comprehension here
```suggestion
        X = tuple(range(n_plants))  # Plants by order
```

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +        n_splits = parameters.n_splits
- [ ] These are things that should be inputted as parameters of the function.
It's okay to make the values from `parameters` the default ones, but don't hardcode it to use them.
This is applicable to all of your usages of `parameters`

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +        skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=1)
- [ ] `random_state` should be an inputted parameter, don't hardcode it to always use the same one.
if you want to always use the same value, you can make it a default value

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +                                                                            parameters.used_modalities)
this may be a bit more readable if you do:
```suggestion
        train_ds = InceptionSubset(modalities, train_indices, parameters.experiment, parameters.experiment_path, parameters.used_modalities)
        test_ds = InceptionSubset(modalities, test_indices, parameters.experiment, parameters.experiment_path, parameters.used_modalities)
        return train_ds, test_ds
```

2020-09-19 07:42 UTC, Snover98 commented on datasets/inception_subset.py
> +        del rest_idx[plant_idx]
- [ ] use list comprehension, also consider renaming to something like `rest_indices`
```suggestion
        rest_indices = [idx for idx in range(modalities.num_plants) if idx != plant_idx]
```

2020-09-19 07:42 UTC, Snover98 commented on model/PlantFeatExtNew.py
> +        # print('D_in  = ', d_in, 'D_out  = ', d_out, ' H = ', h)
- [ ] remove commented code
```suggestion
```
(relevant to all other places too)

2020-09-19 07:42 UTC, Snover98 commented on model/PlantFeatExtNew.py
> +            '''
- [ ] plz remove
```suggestion
```

2020-09-19 07:42 UTC, Snover98 commented on model/PlantFeatExtNew.py
> +            mod_feats[mod] = self.mod_extractors[mod](x[mod])
- [ ] use comprehension
```suggestion
        mod_feats = {mod: self.mod_extractors[mod](torch.squeeze(x[mod])) for mod in self.mods}
```

2020-09-19 07:42 UTC, Snover98 commented on train/tcn_train.py
> +    return list(np.unique(x))
- [ ] I don't see why this function is needed, can you explain shortly?
- [ ] rewrite to be a bit simpler
```suggestion
def unique(list1):
    return np.unique(list1).tolist()
```

2020-09-19 07:42 UTC, Snover98 commented on train/tcn_train.py
> +                y_hat_tot.append(u)
- [ ] global variables are bad.
You have `TestConfig`, so put it there instead

2020-09-19 07:42 UTC, Snover98 commented on train/tcn_train.py
> +            # del x['plant']
- [ ] remove commented code
```suggestion
```

2020-09-19 07:42 UTC, Snover98 commented on train/tcn_train.py
> +                x[key] = x[key].to(test_config.device)
- [ ] use comprehension
```suggestion
            x = {mod: values.to(test_config.device) for mod, values in x.items()}
```

2020-09-19 07:42 UTC, Snover98 commented on train/tcn_train.py
> +    y_hat_tot = []
as mentioned above, global variables are bad practice

2020-09-19 07:42 UTC, Snover98 commented on train/tcn_train.py
> +            files = sorted(glob.glob(f'{root_dir}/*{mod}*{plant_name}*'))
- [ ] no need for `plant_name`
```suggestion
            files = sorted(glob.glob(f'{root_dir}/*{mod}*plant_{plant}_*'))
```

2020-09-19 07:42 UTC, Snover98 commented on train/tcn_train.py
> +            if plant is 0:
- [ ] the `is` operator is best used for making sure that 2 objects are the same one.
For comparisons, it's better to use `==`
```suggestion
            if plant == 0:
```

2020-09-19 07:47 UTC, Snover98 commented on train/tcn_train.py
> +                mod_receptive_field[mod] = len(files)
- [ ] since you want to add the receptive field if it does not exist, it'll be better to make the condition reflect it.
```suggestion
            if mod not in mod_receptive_field:
                mod_receptive_field[mod] = len(files)
```

2020-09-20 19:51 UTC, OrielBanne commented on model/PlantFeatExtNew.py
> +        return torch.stack([m.t() for m in out])
if i remember correctly, I removed some un necessary parameters.

2020-09-20 19:55 UTC, OrielBanne commented on train/tcn_train.py
> +    y_hat_tot = []
could not find a simple solution for this one. coming to think of it - should these parameters be class parameters?

2020-09-24 19:08 UTC, OrielBanne commented on model/PlantFeatExtNew.py
> +            # print('x[mod].shape after torch.squeeze(x[mod]) ', x[mod].shape)  #torch.Size([4, 57, 2048])
well... this is more like a comment with the result of the print ... why change that at this stage? I have a difficult time with remembering the ins and outs ...

2020-09-24 19:10 UTC, OrielBanne commented on datasets/inception_subset.py
> +class Modalities(Dataset):
Done

2020-09-24 19:21 UTC, OrielBanne commented on datasets/inception_subset.py
> +                 **plant_files_dict):
Done

2020-09-29 18:37 UTC, Snover98 commented on train/tcn_train.py
> +    y_hat_tot = []
test config?

2024-11-12 09:45 UTC, closed without merging

2024-11-12 09:45 UTC, OrielBanne commented
this is historical